# Office sensor
# filename: esp32_office.yaml
# Functionality:
#   Motion / presence sensor with mmWave
#   Temperature and humidity sensor (BME280)
#   BLE Tracker
# 
### Declarations ####
substitutions:
# Identity
  devicename: office
  upper_devicename: Office

# Device
  platform: ESP32
  board: nodemcu-32s
  #  board_flash_mode: dout

# Network
  static_ip: 192.168.20.117
  gateway: 192.168.20.1
  subnet: 255.255.255.0

# General
  logger_level: DEBUG

### General configuration ####
esphome:
  name: ${devicename}
  platform: $platform
  board: $board

wifi:
  ssid: !secret wifi_not_ssid
  password: !secret wifi_not_psw
  manual_ip:
    static_ip: $static_ip
    gateway: $gateway
    subnet: $subnet
  # needed for hidden SSID
  fast_connect: true
  
  ap:
    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: ${upper_devicename} AP
    password: !secret wifi_hotspot_psw

captive_portal:

# Enable Home Assistant API
api:

# Enable logging
logger:
  level: $logger_level

ota:
  password: !secret ota_psw

binary_sensor:
  - <<: !include common/connectStatusSensor.yaml
  - platform: ld2410
    has_target:
      name: "${upper_devicename} Presence"
    has_moving_target:
      name: "${upper_devicename} Moving Target"
    has_still_target:
      name: "${upper_devicename} Still Target"

text_sensor:
  - <<: !include common/versionTextSensor.yaml
  - <<: !include common/wifiInfoTextSensor.yaml

switch:
  - <<: !include common/restartSwitch.yaml
  # - <<: !include common/shutdownSwitch.yaml

# for the AHT10 / BH1750
i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True

# for the LD2410 mmWaveSensor
uart:
  #id: uart1
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

sensor:
  - platform: aht10
    temperature:
      name: "${upper_devicename} Temperature"
      id: ${devicename}_temperature
    humidity:
      name: "${upper_devicename} Humidity"
      id: ${devicename}_humidity
    update_interval: 5s
  - platform: bh1750
    name: "${upper_devicename} Illuminance"
    id: ${devicename}_illuminance
    address: 0x23
    update_interval: 5s
  - platform: ld2410
    moving_distance:
      name: "${upper_devicename} Moving Distance"
    still_distance:
      name: "${upper_devicename} Still Distance"
    moving_energy:
      name: "${upper_devicename} Move Energy"
    still_energy:
      name: "${upper_devicename} Still Energy"
    detection_distance:
      name: "${upper_devicename} Detection Distance"

esp32_ble_tracker:
  
bluetooth_proxy:
  active: true

ld2410:
  timeout: 5s
  max_move_distance : 5.25m
  max_still_distance: 5.25m
  g0_move_threshold: 25
  g1_move_threshold: 25
  g2_move_threshold: 20
  g3_move_threshold: 20
  g4_move_threshold: 20
  g5_move_threshold: 20
  g6_move_threshold: 10
  g7_move_threshold: 10
  g8_move_threshold: 10

  g0_still_threshold: 0
  g1_still_threshold: 0
  g2_still_threshold: 25
  g3_still_threshold: 25
  g4_still_threshold: 25
  g5_still_threshold: 25
  g6_still_threshold: 15
  g7_still_threshold: 15
  g8_still_threshold: 15
