# ESP32 Sina Bed
# filename: ESP32_sina_bed.yaml

#
# 
### Declarations ####
substitutions:
# Identity
  devicename: sina_bed
  upper_devicename: Sina Bed

# Device
  platform: ESP32
  board: nodemcu-32s
  #  board_flash_mode: dout

# Network
  static_ip: 192.168.20.118
  gateway: 192.168.20.1
  subnet: 255.255.255.0

# General
  logger_level: DEBUG

### General configuration ####
esphome:
  name: ${devicename}
  platform: $platform
  board: $board

wifi:
  ssid: !secret wifi_not_ssid
  password: !secret wifi_not_psw
  manual_ip:
    static_ip: $static_ip
    gateway: $gateway
    subnet: $subnet
  # needed for hidden SSID
  fast_connect: true
  
  ap:
    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: ${upper_devicename} AP
    password: !secret wifi_hotspot_psw

captive_portal:

# Enable Home Assistant API
api:

# Enable logging
logger:
  level: $logger_level

ota:
  password: !secret ota_psw

binary_sensor:
  - <<: !include common/connectStatusSensor.yaml
    # Motion sensor (HC SR-501)
  - platform: gpio  
    pin: 
      number: GPIO18
      mode:
        input: true
        pullup: true
    name: "${upper_devicename} Below Motion"
    device_class: motion

# for the I2C bus
i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True

text_sensor:
  - <<: !include common/versionTextSensor.yaml
  - <<: !include common/wifiInfoTextSensor.yaml

switch:
  - <<: !include common/restartSwitch.yaml
  # - <<: !include common/shutdownSwitch.yaml

sensor:
  - platform: aht10
    temperature:
      name: "${upper_devicename} Temperature"
      id: ${devicename}_temperature3
    humidity:
      name: "${upper_devicename} Humidity"
      id: ${devicename}_humidity3
    update_interval: 10s

esp32_ble_tracker:

bluetooth_proxy:
  active: true

light:
# Selected NeoPixelBus since FastLed was not working
# due to a bug (ESPHOME #2877) you have to state a specific method else both neopixelbusses are mixed.
  - platform: neopixelbus
    variant: WS2812X
    pin: GPIO32
    num_leds: 165
    type: GRB
    name: "${upper_devicename} underglow"
    id: ${devicename}_underglow
    default_transition_length: 1s
    method:
      type: esp32_rmt
      channel: 0
    effects:
      - flicker:
      - flicker:
          name: Flicker Effect Custom all
          alpha: 95%
          intensity: 1.5%
      - strobe:
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: False
              duration: 250ms
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - random:
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 1s
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect Speed 100
          speed: 100
          width: 50
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False
      - addressable_scan:
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 100ms
          scan_width: 1
      - addressable_scan:
          name: Scan 20dots
          move_interval: 10ms
          scan_width: 20
      - addressable_twinkle:
      - addressable_twinkle:
          name: Twinkle White 50%
          twinkle_probability: 50%
          progress_interval: 16ms
      - addressable_random_twinkle:
      - addressable_random_twinkle:
          name: Random Twinkle 50%
          twinkle_probability: 50%
          progress_interval: 32ms
      - addressable_random_twinkle:
          name: Random Twinkle 90%
          twinkle_probability: 90%
          progress_interval: 32ms
      - addressable_fireworks:
      - addressable_fireworks:
          name: Fireworks White Fast
          update_interval: 1ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 50
      - addressable_flicker:
      - addressable_flicker:
          name: Flicker Effect With Custom Values
          update_interval: 16ms
          intensity: 5%
          
  - platform: neopixelbus
    variant: WS2812X
    pin: GPIO33
    num_leds: 100
    type: GRB
    name: "${upper_devicename} backglow"
    id: ${devicename}_backglow
    default_transition_length: 1s
    method:
      type: esp32_rmt
      channel: 1
    effects:
      - flicker:
      - flicker:
          name: Flicker Effect Custom all
          alpha: 95%
          intensity: 1.5%
      - strobe:
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: False
              duration: 250ms
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - random:
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 1s
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect Speed 100
          speed: 100
          width: 50
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False
      - addressable_scan:
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 100ms
          scan_width: 1
      - addressable_scan:
          name: Scan 20dots
          move_interval: 10ms
          scan_width: 20
      - addressable_twinkle:
      - addressable_twinkle:
          name: Twinkle White 50%
          twinkle_probability: 50%
          progress_interval: 16ms
      - addressable_random_twinkle:
      - addressable_random_twinkle:
          name: Random Twinkle 50%
          twinkle_probability: 50%
          progress_interval: 32ms
      - addressable_random_twinkle:
          name: Random Twinkle 90%
          twinkle_probability: 90%
          progress_interval: 32ms
      - addressable_fireworks:
      - addressable_fireworks:
          name: Fireworks White Fast
          update_interval: 1ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 50
      - addressable_flicker:
      - addressable_flicker:
          name: Flicker Effect With Custom Values
          update_interval: 16ms
          intensity: 5%
