# BLE Scanner
# filename: ESP32_service.yaml
# Settings from https://gist.github.com/kmdm/c01c0693b1380d826af200a3e9b2a656#file-esphome_ble_config-yaml
#  and from https://github.com/rpatel3001/BleDistance
#
# 
### Declarations ####
substitutions:
# Identity
  devicename: office
  upper_devicename: Office

# Device
  platform: ESP32
  board: nodemcu-32s
  #  board_flash_mode: dout

# Network
  static_ip: 192.168.20.117
  gateway: 192.168.20.1
  subnet: 255.255.255.0

# General
  logger_level: DEBUG

### General configuration ####
esphome:
  name: ${devicename}
  platform: $platform
  board: $board
  includes:
    - custom_components/lib/OneEuro.h
    - custom_components/ble_dist.h
  # Pietz Pixel 6  Use BLE scanner to get the UUID: C2E41D5F-0E1B-9381-3E49-3C5580D607B6 bit this is backwards so you have to use the original UUIID from the app.
  on_boot:
    then:
      lambda: |-
        addTracker("pietzphone", "b607d680-553c-493e-8193-1b0e5f1de4c2"); 

# MQTT broker configuration
#mqtt:
#  broker: !secret mqtt_broker
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  discovery: False # Only if you use the HA API usually
#  id: mqtt_client

wifi:
  ssid: !secret wifi_not_ssid
  password: !secret wifi_not_psw
  manual_ip:
    static_ip: $static_ip
    gateway: $gateway
    subnet: $subnet
  # needed for hidden SSID
  fast_connect: true
  
  ap:
    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: ${upper_devicename} AP
    password: !secret wifi_hotspot_psw

captive_portal:

# Enable Home Assistant API
api:

# Enable logging
logger:
  level: $logger_level

ota:
  password: !secret ota_psw

binary_sensor:
  - <<: !include common/connectStatusSensor.yaml
  - platform: gpio
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
    name: "${devicename} Motion"
    device_class: motion

text_sensor:
  - <<: !include common/versionTextSensor.yaml
  - <<: !include common/wifiInfoTextSensor.yaml

switch:
  - <<: !include common/restartSwitch.yaml
  # - <<: !include common/shutdownSwitch.yaml

sensor:
  - platform: dht
    pin: GPIO4
    model: DHT22
    temperature:
      name: "${devicename} Temperature"
    humidity:
      name: "${devicename} Humidity"
    update_interval: 10s


esp32_ble_tracker:

bluetooth_proxy: