esphome:
  name: sina
  platform: ESP32
  board: mhetesp32minikit # MH-ET Live (ESP32 MiniKit, D1 mini compatible)
#  board_flash_mode: dout
    
wifi:
  ssid: !secret wifi_not_ground_ssid
  password: !secret wifi_not_psw
  manual_ip:
    static_ip: 192.168.20.110
    gateway: 192.168.20.1
    subnet: 255.255.255.0
  # needed for hidden SSID
  fast_connect: true
  
  ap:
    ssid: "Sina Hotspot"
    password: !secret wifi_hotspot_psw

captive_portal:

api:

logger:

ota:
  password: !secret ota_psw

esp32_ble_tracker:
  on_ble_advertise:
    - then:
        - lambda: |-
            for (auto data : x.get_manufacturer_datas()) {
              if (strcmp(hexencode(data.data).c_str(), "02.15.D1.31.21.64.29.27.48.9F.91.28.7E.11.DB.FB.7A.81.00.01.00.01.BF (23)") == 0) {
                ESP_LOGD("ble_adv", "pietz_phone_ble found");
                id(ble_off_script).execute();
              }
              // ESP_LOGD("ble_adv", "    - %s", hexencode(data.data).c_str());
            }

script:
  - id: ble_off_script
    mode: restart
    then:
      - binary_sensor.template.publish:
          id: pietz_phone_ble
          state: true
      - delay: 3s
      - binary_sensor.template.publish:
          id: pietz_phone_ble
          state: false

binary_sensor:
  - platform: template
    device_class: presence
    name: "Pietz Phone BLE"
    id: pietz_phone_ble
    filters:
      - delayed_off: 3s

switch:
  - platform: restart
    name: "Sina Restarts"


