# Serviceroom Node-Red (NR) version
# The automation is handled by by NR
# Device: Sonoff Basic wih the following connections
# GPIO14  DHT22 (AM2302)
# GPIO03  SR501 (PIR sensor)

esphome:
  name: serviceroom
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
    
wifi:
  ssid: !secret wifi_not_ssid
  password: !secret wifi_not_psw
  manual_ip:
    static_ip: 192.168.20.100
    gateway: 192.168.20.1
    subnet: 255.255.255.0
  
  # needed for hidden SSID
  fast_connect: true

  ap:
    ssid: "Serviceroom Hotspot"
    password: !secret wifi_hotspot_psw

captive_portal:

api:

logger:

ota:

sensor:
  - platform: wifi_signal
    name: "Serviceroom WiFi Signal"
  - platform: dht
    model: AM2302
    pin: GPIO14
    temperature:
      name: "Serviceroom Temperature"
    humidity:
      name: "Serviceroom Humidity"
    update_interval: 1min
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
    device_class: motion
    id: pir_sensor
    name: "Serviceroom PIR Sensor"

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Serviceroom Button"
    on_press:
      then:
        - light.toggle: basic_led
        - switch.toggle: basic_relay
  - platform: status
    name: "Serviceroom Status"

switch:
  - platform: gpio
    name: "Serviceroom Relay"
    id: basic_relay
    pin: GPIO12
  - platform: restart
    name: "Serviceroom Restart"

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "Serviceroom Green LED"
    output: basic_green_led
    id: basic_led